---
version: '2'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=password@main-dev
